-- ==============================================================================
-- GitTrend Korea 데이터베이스 스키마
-- Supabase SQL Editor 에서 실행하세요.
-- ==============================================================================

-- 1. repositories: 개별 레포지토리 정보 (최초 수집 및 캐시용)
CREATE TABLE repositories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  github_id BIGINT UNIQUE NOT NULL,
  full_name TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  owner_login TEXT NOT NULL,
  owner_avatar_url TEXT,
  description TEXT,
  description_ko TEXT,
  summary_ko TEXT,
  html_url TEXT NOT NULL,
  homepage TEXT,
  language TEXT,
  topics JSONB DEFAULT '[]'::jsonb,
  stars_count INTEGER DEFAULT 0,
  forks_count INTEGER DEFAULT 0,
  issues_count INTEGER DEFAULT 0,
  open_graph_image_url TEXT,
  last_fetched_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. trending_snapshots: 특정 시점의 트렌딩 순위 스냅샷
CREATE TABLE trending_snapshots (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  period TEXT NOT NULL, -- 'daily', 'weekly', 'monthly'
  language TEXT NOT NULL, -- 'all', 'javascript', 'python' 등
  snapshot_date DATE NOT NULL DEFAULT CURRENT_DATE,
  repo_id BIGINT REFERENCES repositories(id) ON DELETE CASCADE,
  current_rank INTEGER NOT NULL,
  gained_stars INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  -- 한 날짜에 같은 조건으로 같은 레포가 여러 번 기록되지 않도록 고유 인덱스 역할
  UNIQUE(period, language, snapshot_date, repo_id)
);

-- 3. translation_cache: README 및 기타 장문 번역 결과 캐싱
CREATE TABLE translation_cache (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  repo_id BIGINT REFERENCES repositories(id) ON DELETE CASCADE UNIQUE,
  readme_original TEXT NOT NULL,
  readme_ko TEXT NOT NULL,
  tokens_used INTEGER DEFAULT 0,
  is_verified BOOLEAN DEFAULT FALSE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. api_usage_log: 무료 티어 방어를 위한 할당량 추적
CREATE TABLE api_usage_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  service_name TEXT NOT NULL, -- 'gemini', 'github', 'redis'
  endpoint TEXT,
  tokens_used INTEGER DEFAULT 0,
  requests_count INTEGER DEFAULT 1,
  log_date DATE NOT NULL DEFAULT CURRENT_DATE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  
  UNIQUE(service_name, endpoint, log_date)
);

-- 인덱스 생성 (검색 및 조인 속도 최적화)
CREATE INDEX idx_repositories_full_name ON repositories(full_name);
CREATE INDEX idx_repositories_language ON repositories(language);
CREATE INDEX idx_trending_snapshots_lookup ON trending_snapshots(period, language, snapshot_date);
CREATE INDEX idx_trending_snapshots_rank ON trending_snapshots(current_rank);
CREATE INDEX idx_translation_cache_repo_id ON translation_cache(repo_id);

-- RLS (Row Level Security) 설정
-- 기본적으로 모든 테이블은 읽기 전용 (Public)
-- 쓰기/수정은 Service Role Key를 가진 서버 스크립트만 가능
ALTER TABLE repositories ENABLE ROW LEVEL SECURITY;
ALTER TABLE trending_snapshots ENABLE ROW LEVEL SECURITY;
ALTER TABLE translation_cache ENABLE ROW LEVEL SECURITY;
ALTER TABLE api_usage_log ENABLE ROW LEVEL SECURITY;

-- 모두에게 읽기 허용 정책
CREATE POLICY "Allow public read access on repositories" ON repositories FOR SELECT USING (true);
CREATE POLICY "Allow public read access on trending_snapshots" ON trending_snapshots FOR SELECT USING (true);
CREATE POLICY "Allow public read access on translation_cache" ON translation_cache FOR SELECT USING (true);
-- api_usage_log는 관리자용이므로 public에 오픈하지 않음
